# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-20 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0002_auto_20160520_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hoteles',
            old_name='url',
            new_name='url_hotel',
        ),
    ]
