# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0005_auto_20160520_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Date',
            field=models.DateTimeField(),
        ),
    ]
