# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0006_auto_20160522_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
