# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0007_auto_20160522_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel_selecc',
            name='User',
            field=models.CharField(max_length=32),
        ),
    ]
