# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-22 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hoteles', '0008_auto_20160522_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel_selecc',
            old_name='User',
            new_name='Nombre_usuario',
        ),
    ]
